version: '3.8'

services:
  app:
    build: .
    container_name: video-ads-backend
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DSN: postgres://postgres:postgres@db:5432/ads_db?sslmode=disable
      REDIS_ADDR: redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    container_name: ads_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ads_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: ads_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
